services:
  db:
    image: postgres:latest
    container_name: inventory
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6666:5432
    restart: unless-stopped
volumes:
  postgres-data:

